/* GENERATED by scripts/generate-design-tokens.mjs from DESIGN.md. DO NOT EDIT. */
export const designTokens = {
  "version": "alpha",
  "name": "TelemetryX Operating Ledger",
  "description": "Industrial operating precision with calm human accountability for an OPERATE-first fleet command surface.",
  "colors": {
    "primary": "#185C43",
    "primary-hover": "#0F4934",
    "primary-soft": "#E4F0E9",
    "on-primary": "#FFFFFF",
    "brand-ink": "#17231D",
    "brand-forest": "#123D2D",
    "brand-lime-signal": "#C7F04D",
    "canvas": "#F4F1E8",
    "surface": "#FFFEFA",
    "surface-subtle": "#ECEAE2",
    "surface-strong": "#E2E2D9",
    "text": "#17231D",
    "text-muted": "#4E5B54",
    "text-subtle": "#5F6B64",
    "border": "#C9CEC8",
    "border-strong": "#9DA8A1",
    "focus": "#087A58",
    "success": "#176443",
    "success-soft": "#E3F2E8",
    "on-success-soft": "#10462F",
    "warning": "#8A4B08",
    "warning-soft": "#FFF1D4",
    "on-warning-soft": "#603000",
    "danger": "#9D2F24",
    "danger-soft": "#FCE9E5",
    "on-danger-soft": "#6E1F18",
    "info": "#245A73",
    "info-soft": "#E7F2F5",
    "on-info-soft": "#173F52",
    "disabled": "#D8DCD7",
    "on-disabled": "#58615B",
    "overlay": "#0F1B1585"
  },
  "typography": {
    "display": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "2rem",
      "fontWeight": 720,
      "lineHeight": 1.12,
      "letterSpacing": "-0.025em"
    },
    "heading-lg": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "1.5rem",
      "fontWeight": 700,
      "lineHeight": 1.2,
      "letterSpacing": "-0.015em"
    },
    "heading-md": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "1.125rem",
      "fontWeight": 700,
      "lineHeight": 1.3
    },
    "body": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "0.9375rem",
      "fontWeight": 450,
      "lineHeight": 1.5
    },
    "body-sm": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "0.8125rem",
      "fontWeight": 450,
      "lineHeight": 1.45
    },
    "label": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "0.75rem",
      "fontWeight": 680,
      "lineHeight": 1.3,
      "letterSpacing": "0.055em"
    },
    "numeric": {
      "fontFamily": "Segoe UI Variable, Segoe UI, system-ui, sans-serif",
      "fontSize": "1.75rem",
      "fontWeight": 720,
      "lineHeight": 1,
      "letterSpacing": "-0.03em",
      "fontFeature": "'tnum', 'lnum'"
    },
    "code": {
      "fontFamily": "Cascadia Mono, SFMono-Regular, Consolas, monospace",
      "fontSize": "0.75rem",
      "fontWeight": 600,
      "lineHeight": 1.4
    }
  },
  "rounded": {
    "none": "0px",
    "xs": "3px",
    "sm": "5px",
    "md": "8px",
    "lg": "12px",
    "full": "999px"
  },
  "spacing": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px"
  },
  "components": {
    "layout-sidebar": {
      "width": "248px"
    },
    "layout-topbar": {
      "height": "64px"
    },
    "layout-content": {
      "width": "1440px"
    },
    "modal-overlay": {
      "backgroundColor": "{colors.overlay}",
      "textColor": "{colors.on-primary}"
    },
    "brand-wordmark": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.brand-ink}",
      "typography": "{typography.heading-md}"
    },
    "brand-rail": {
      "backgroundColor": "{colors.brand-forest}",
      "textColor": "{colors.on-primary}"
    },
    "live-signal": {
      "backgroundColor": "{colors.brand-lime-signal}",
      "textColor": "{colors.brand-ink}"
    },
    "page": {
      "backgroundColor": "{colors.canvas}",
      "textColor": "{colors.text}",
      "typography": "{typography.body}"
    },
    "panel": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.text}",
      "rounded": "{rounded.md}",
      "padding": "{spacing.5}"
    },
    "panel-subtle": {
      "backgroundColor": "{colors.surface-subtle}",
      "textColor": "{colors.text}"
    },
    "panel-strong": {
      "backgroundColor": "{colors.surface-strong}",
      "textColor": "{colors.brand-ink}"
    },
    "metadata": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.text-muted}",
      "typography": "{typography.body-sm}"
    },
    "subtle-metadata": {
      "backgroundColor": "{colors.canvas}",
      "textColor": "{colors.text-subtle}"
    },
    "border-sample": {
      "backgroundColor": "{colors.border}",
      "textColor": "{colors.brand-ink}"
    },
    "border-strong-sample": {
      "backgroundColor": "{colors.border-strong}",
      "textColor": "{colors.brand-ink}"
    },
    "button-primary": {
      "backgroundColor": "{colors.primary}",
      "textColor": "{colors.on-primary}",
      "rounded": "{rounded.sm}",
      "height": "36px",
      "padding": "12px",
      "typography": "{typography.body-sm}"
    },
    "button-primary-hover": {
      "backgroundColor": "{colors.primary-hover}",
      "textColor": "{colors.on-primary}"
    },
    "selection": {
      "backgroundColor": "{colors.primary-soft}",
      "textColor": "{colors.brand-forest}"
    },
    "button-secondary": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.brand-forest}",
      "rounded": "{rounded.sm}",
      "height": "36px"
    },
    "button-disabled": {
      "backgroundColor": "{colors.disabled}",
      "textColor": "{colors.on-disabled}"
    },
    "focus-ring": {
      "backgroundColor": "{colors.focus}",
      "textColor": "{colors.on-primary}"
    },
    "badge-success": {
      "backgroundColor": "{colors.success-soft}",
      "textColor": "{colors.on-success-soft}",
      "rounded": "{rounded.full}",
      "typography": "{typography.label}"
    },
    "badge-success-strong": {
      "backgroundColor": "{colors.success}",
      "textColor": "{colors.on-primary}"
    },
    "badge-warning": {
      "backgroundColor": "{colors.warning-soft}",
      "textColor": "{colors.on-warning-soft}",
      "rounded": "{rounded.full}"
    },
    "badge-warning-strong": {
      "backgroundColor": "{colors.warning}",
      "textColor": "{colors.on-primary}"
    },
    "badge-danger": {
      "backgroundColor": "{colors.danger-soft}",
      "textColor": "{colors.on-danger-soft}",
      "rounded": "{rounded.full}"
    },
    "badge-danger-strong": {
      "backgroundColor": "{colors.danger}",
      "textColor": "{colors.on-primary}"
    },
    "badge-info": {
      "backgroundColor": "{colors.info-soft}",
      "textColor": "{colors.on-info-soft}",
      "rounded": "{rounded.full}"
    },
    "badge-info-strong": {
      "backgroundColor": "{colors.info}",
      "textColor": "{colors.on-primary}"
    },
    "compact-control": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.text}",
      "rounded": "{rounded.xs}",
      "height": "32px"
    },
    "mobile-control": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.text}",
      "rounded": "{rounded.sm}",
      "height": "44px"
    },
    "square-data-region": {
      "backgroundColor": "{colors.surface}",
      "textColor": "{colors.text}",
      "rounded": "{rounded.none}"
    }
  },
  "contracts": {
    "typography": {
      "label-text-transform": "uppercase",
      "numeric-font-variant": "tabular-nums lining-nums"
    },
    "elevation": {
      "level-1": "0 1px 2px rgb(23 35 29 / 0.06)",
      "level-2": "0 8px 24px rgb(23 35 29 / 0.12)",
      "level-3": "0 18px 48px rgb(23 35 29 / 0.18)"
    },
    "motion": {
      "duration-fast": "120ms",
      "duration-spatial": "180ms",
      "ease-out": "cubic-bezier(0.2, 0, 0, 1)"
    }
  }
} as const
